<?php
/**
 * VmOrder
 *
 * @author Yireo
 * @package VmOrder
 * @copyright Copyright 2009
 * @license Yireo EULA (www.yireo.com)
 * @link http://www.yireo.com
 */

$orders = $this->getOrders();
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-head">
    <h3><?php echo $this->__('My Previous Orders') ?></h3>
</div>

<?php if(!empty($orders) && $orders->getSize() > 0) : ?>

<p><?php echo $this->__('These are orders originating from our old website'); ?></p>

<?php echo $this->getPagerHtml(); ?>
<table cellspacing="0" class="data-table" id="vm-orders-table">
    <col />
    <col />
    <col width="15%" />
    <col width="30%" />
    <thead>
        <tr>
            <th><?php echo $this->__('Date'); ?></th>
            <th><?php echo $this->__('Order number'); ?></th>
            <th><?php echo $this->__('Total'); ?></th>
            <th><?php echo $this->__('Status'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($orders as $order) : ?>
            <tr>
                <td><?php echo strftime('%d %B %Y', $order->getCreateDate()); ?></td>
                <td><a href="<?php echo $this->getOrderLink($order); ?>"><?php echo $this->getOrderNumber($order); ?></a></td>
                <td><?php echo $this->getFormattedPrice($order); ?></td>
                <td><?php echo $order->getOrderStatusName(); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">decorateTable('vm-orders-table')</script>
<?php echo $this->getPagerHtml(); ?>
        
<?php else : ?>
<p><?php echo $this->__('No previous orders available'); ?></p>
<?php endif; ?>
